import {
  Agency,
  CarrierLoopStep,
  Claim,
  Document,
  SwimlanePhase,
  TimelineEvent,
  User,
  Vendor,
  WorkflowStage,
  Referral,
  ReferralStatus,
} from "./types";

export const agencies: Agency[] = [
  {
    id: "agency-1",
    name: "Summit Insurance Group",
    primary_contact_email: "contact@summitinsure.com",
    metadata: { region: "West" },
    created_at: "2023-07-15T10:00:00.000Z",
    updated_at: "2023-11-05T14:30:00.000Z",
  },
  {
    id: "agency-2",
    name: "Harbor Mutual",
    primary_contact_email: "claims@harbormutual.com",
    metadata: { region: "Midwest" },
    created_at: "2023-08-20T12:00:00.000Z",
    updated_at: "2023-11-12T09:45:00.000Z",
  },
  {
    id: "agency-3",
    name: "Evergreen Assurance",
    primary_contact_email: "support@evergreenassurance.com",
    metadata: { region: "Northeast" },
    created_at: "2023-09-02T08:00:00.000Z",
    updated_at: "2023-11-20T18:00:00.000Z",
  },
  {
    id: "agency-4",
    name: "Coastal Shield",
    primary_contact_email: "info@coastalshield.com",
    metadata: { region: "South" },
    created_at: "2023-10-05T15:00:00.000Z",
    updated_at: "2023-11-18T16:30:00.000Z",
  },
];

export const vendors: Vendor[] = [
  {
    id: "vendor-1",
    name: "Rapid Restore",
    contact_email: "ops@rapidrestore.com",
    phone: "+1 (555) 214-3901",
    metadata: { specialty: "Fire" },
    payment_details: { method: "ACH" },
    created_at: "2023-07-18T10:00:00.000Z",
    updated_at: "2023-11-07T11:00:00.000Z",
  },
  {
    id: "vendor-2",
    name: "ClearSky Roofing",
    contact_email: "hello@clearskyroofing.com",
    phone: "+1 (555) 881-0042",
    metadata: { specialty: "Roof" },
    payment_details: { method: "Wire" },
    created_at: "2023-08-25T09:00:00.000Z",
    updated_at: "2023-11-11T12:00:00.000Z",
  },
  {
    id: "vendor-3",
    name: "EverDry Mitigation",
    contact_email: "dispatch@everdry.com",
    phone: "+1 (555) 733-2100",
    metadata: { specialty: "Water" },
    payment_details: { method: "ACH" },
    created_at: "2023-09-05T13:00:00.000Z",
    updated_at: "2023-11-19T13:30:00.000Z",
  },
  {
    id: "vendor-4",
    name: "Northwind Construction",
    contact_email: "projects@northwindco.com",
    phone: null,
    metadata: { specialty: "General" },
    payment_details: { method: "Check" },
    created_at: "2023-09-15T15:00:00.000Z",
    updated_at: "2023-11-21T10:30:00.000Z",
  },
];

export const users: User[] = [
  {
    id: "user-1",
    email: "alex.mason@claimsai.com",
    password_hash: "hashed",
    full_name: "Alex Mason",
    role: "manager",
    agency_id: "agency-1",
    created_at: "2023-07-16T10:00:00.000Z",
    updated_at: "2023-11-01T12:00:00.000Z",
  },
  {
    id: "user-2",
    email: "jamie.lee@claimsai.com",
    password_hash: "hashed",
    full_name: "Jamie Lee",
    role: "adjuster",
    agency_id: "agency-2",
    created_at: "2023-08-22T10:00:00.000Z",
    updated_at: "2023-11-08T12:00:00.000Z",
  },
  {
    id: "user-3",
    email: "sasha.rivera@claimsai.com",
    password_hash: "hashed",
    full_name: "Sasha Rivera",
    role: "adjuster",
    agency_id: "agency-3",
    created_at: "2023-09-03T10:00:00.000Z",
    updated_at: "2023-11-10T12:00:00.000Z",
  },
  {
    id: "user-4",
    email: "priya.kapoor@claimsai.com",
    password_hash: "hashed",
    full_name: "Priya Kapoor",
    role: "adjuster",
    agency_id: "agency-4",
    created_at: "2023-10-06T10:00:00.000Z",
    updated_at: "2023-11-15T12:00:00.000Z",
  },
  {
    id: "user-5",
    email: "vendor.user@northwindco.com",
    password_hash: "hashed",
    full_name: "Taylor Brooks",
    role: "vendor_user",
    agency_id: null,
    created_at: "2023-09-20T10:00:00.000Z",
    updated_at: "2023-11-22T12:00:00.000Z",
  },
];

export const claims: Claim[] = [
  {
    id: "claim-1",
    case_number: "CA-10234",
    agency_id: "agency-1",
    insured_name: "Michael Hart",
    insured_contact: "michael.hart@email.com",
    loss_date: "2023-10-15T00:00:00.000Z",
    loss_details: "Kitchen fire originating from stove.",
    status: "in_review",
    assigned_adjuster_id: "user-1",
    assigned_vendor_id: "vendor-1",
    referral_source: "Agent referral",
    qa_score: 92,
    created_at: "2023-10-16T09:00:00.000Z",
    updated_at: "2023-11-20T14:00:00.000Z",
  },
  {
    id: "claim-2",
    case_number: "CA-10235",
    agency_id: "agency-2",
    insured_name: "Jessica Chen",
    insured_contact: "jessica.chen@email.com",
    loss_date: "2023-09-22T00:00:00.000Z",
    loss_details: "Roof damage after hailstorm.",
    status: "negotiation",
    assigned_adjuster_id: "user-2",
    assigned_vendor_id: "vendor-2",
    referral_source: "Inbound web",
    qa_score: 87,
    created_at: "2023-09-23T09:00:00.000Z",
    updated_at: "2023-11-18T11:00:00.000Z",
  },
  {
    id: "claim-3",
    case_number: "CA-10236",
    agency_id: "agency-3",
    insured_name: "Rafael Gomez",
    insured_contact: "rafael.gomez@email.com",
    loss_date: "2023-08-10T00:00:00.000Z",
    loss_details: "Water damage from burst pipe.",
    status: "settled",
    assigned_adjuster_id: "user-3",
    assigned_vendor_id: "vendor-3",
    referral_source: "Carrier transfer",
    qa_score: 95,
    created_at: "2023-08-11T09:00:00.000Z",
    updated_at: "2023-11-10T10:00:00.000Z",
  },
  {
    id: "claim-4",
    case_number: "CA-10237",
    agency_id: "agency-2",
    insured_name: "Emily Davis",
    insured_contact: "emily.davis@email.com",
    loss_date: "2023-11-02T00:00:00.000Z",
    loss_details: "Wind damage to siding.",
    status: "new",
    assigned_adjuster_id: "user-2",
    assigned_vendor_id: null,
    referral_source: "Partner portal",
    qa_score: null,
    created_at: "2023-11-03T09:00:00.000Z",
    updated_at: "2023-11-22T08:00:00.000Z",
  },
  {
    id: "claim-5",
    case_number: "CA-10238",
    agency_id: "agency-4",
    insured_name: "Samuel O'Neil",
    insured_contact: "samuel.oneil@email.com",
    loss_date: "2023-10-01T00:00:00.000Z",
    loss_details: "Garage fire after electrical short.",
    status: "negotiation",
    assigned_adjuster_id: "user-4",
    assigned_vendor_id: "vendor-1",
    referral_source: "Adjuster referral",
    qa_score: 78,
    created_at: "2023-10-02T09:00:00.000Z",
    updated_at: "2023-11-19T16:00:00.000Z",
  },
  {
    id: "claim-6",
    case_number: "CA-10239",
    agency_id: "agency-1",
    insured_name: "Olivia Price",
    insured_contact: "olivia.price@email.com",
    loss_date: "2023-07-28T00:00:00.000Z",
    loss_details: "Smoke damage throughout home.",
    status: "closed",
    assigned_adjuster_id: "user-1",
    assigned_vendor_id: "vendor-4",
    referral_source: "Agent referral",
    qa_score: 90,
    created_at: "2023-07-29T09:00:00.000Z",
    updated_at: "2023-11-01T14:00:00.000Z",
  },
  {
    id: "claim-7",
    case_number: "CA-10240",
    agency_id: "agency-3",
    insured_name: "Lena Patel",
    insured_contact: "lena.patel@email.com",
    loss_date: "2023-11-10T00:00:00.000Z",
    loss_details: "Flooding in basement after heavy rain.",
    status: "in_review",
    assigned_adjuster_id: "user-3",
    assigned_vendor_id: "vendor-3",
    referral_source: "Inbound web",
    qa_score: 83,
    created_at: "2023-11-11T09:00:00.000Z",
    updated_at: "2023-11-21T10:00:00.000Z",
  },
];

export const documents: Document[] = [
  {
    id: "doc-1",
    claim_id: "claim-1",
    uploaded_by: "user-1",
    vendor_id: "vendor-1",
    filename: "Initial Assessment.pdf",
    file_type: "application/pdf",
    file_size: 1024 * 1024 * 1.2,
    storage_key: "docs/claim-1/assessment.pdf",
    tags: ["assessment"],
    meta: null,
    created_at: "2023-10-17T10:00:00.000Z",
    updated_at: "2023-10-17T10:00:00.000Z",
  },
  {
    id: "doc-2",
    claim_id: "claim-2",
    uploaded_by: "user-2",
    vendor_id: "vendor-2",
    filename: "Roof Photos.zip",
    file_type: "application/zip",
    file_size: 1024 * 1024 * 5.4,
    storage_key: "docs/claim-2/roof-photos.zip",
    tags: ["photos", "roof"],
    meta: null,
    created_at: "2023-09-24T12:00:00.000Z",
    updated_at: "2023-09-24T12:00:00.000Z",
  },
  {
    id: "doc-3",
    claim_id: "claim-3",
    uploaded_by: "user-3",
    vendor_id: "vendor-3",
    filename: "Settlement Summary.pdf",
    file_type: "application/pdf",
    file_size: 1024 * 820,
    storage_key: "docs/claim-3/settlement.pdf",
    tags: ["settlement"],
    meta: null,
    created_at: "2023-10-01T12:00:00.000Z",
    updated_at: "2023-10-01T12:00:00.000Z",
  },
  {
    id: "doc-4",
    claim_id: "claim-4",
    uploaded_by: "user-2",
    vendor_id: null,
    filename: "Policy Copy.pdf",
    file_type: "application/pdf",
    file_size: 1024 * 480,
    storage_key: "docs/claim-4/policy.pdf",
    tags: ["policy"],
    meta: null,
    created_at: "2023-11-04T11:00:00.000Z",
    updated_at: "2023-11-04T11:00:00.000Z",
  },
  {
    id: "doc-5",
    claim_id: "claim-5",
    uploaded_by: "user-4",
    vendor_id: "vendor-1",
    filename: "Negotiation Notes.docx",
    file_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    file_size: 1024 * 1024 * 0.8,
    storage_key: "docs/claim-5/notes.docx",
    tags: ["notes"],
    meta: null,
    created_at: "2023-10-10T10:00:00.000Z",
    updated_at: "2023-10-10T10:00:00.000Z",
  },
  {
    id: "doc-6",
    claim_id: "claim-7",
    uploaded_by: "user-3",
    vendor_id: "vendor-3",
    filename: "Mitigation Plan.pdf",
    file_type: "application/pdf",
    file_size: 1024 * 1024 * 2.1,
    storage_key: "docs/claim-7/mitigation.pdf",
    tags: ["plan", "mitigation"],
    meta: null,
    created_at: "2023-11-12T09:00:00.000Z",
    updated_at: "2023-11-12T09:00:00.000Z",
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: "event-1",
    claim_id: "claim-1",
    event_type: "note",
    body: "Site inspection scheduled with Rapid Restore.",
    meta: null,
    created_by: "user-1",
    created_at: "2023-10-17T09:00:00.000Z",
    updated_at: "2023-10-17T09:00:00.000Z",
  },
  {
    id: "event-2",
    claim_id: "claim-1",
    event_type: "status_change",
    body: "Status updated to in_review.",
    meta: { from: "new", to: "in_review" },
    created_by: "user-1",
    created_at: "2023-10-18T08:30:00.000Z",
    updated_at: "2023-10-18T08:30:00.000Z",
  },
  {
    id: "event-3",
    claim_id: "claim-2",
    event_type: "call",
    body: "Spoke with insured regarding roof inspection results.",
    meta: null,
    created_by: "user-2",
    created_at: "2023-10-01T13:00:00.000Z",
    updated_at: "2023-10-01T13:00:00.000Z",
  },
  {
    id: "event-4",
    claim_id: "claim-2",
    event_type: "status_change",
    body: "Status updated to negotiation.",
    meta: { from: "in_review", to: "negotiation" },
    created_by: "user-2",
    created_at: "2023-10-05T10:00:00.000Z",
    updated_at: "2023-10-05T10:00:00.000Z",
  },
  {
    id: "event-5",
    claim_id: "claim-3",
    event_type: "email",
    body: "Sent settlement documents to insured.",
    meta: null,
    created_by: "user-3",
    created_at: "2023-09-15T09:00:00.000Z",
    updated_at: "2023-09-15T09:00:00.000Z",
  },
  {
    id: "event-6",
    claim_id: "claim-4",
    event_type: "note",
    body: "Awaiting vendor assignment.",
    meta: null,
    created_by: "user-2",
    created_at: "2023-11-05T10:00:00.000Z",
    updated_at: "2023-11-05T10:00:00.000Z",
  },
  {
    id: "event-7",
    claim_id: "claim-5",
    event_type: "call",
    body: "Negotiation call with insured scheduled.",
    meta: null,
    created_by: "user-4",
    created_at: "2023-10-12T11:00:00.000Z",
    updated_at: "2023-10-12T11:00:00.000Z",
  },
  {
    id: "event-8",
    claim_id: "claim-7",
    event_type: "document_uploaded",
    body: "Mitigation plan uploaded by vendor.",
    meta: { storage_key: "docs/claim-7/mitigation.pdf" },
    created_by: "user-3",
    created_at: "2023-11-12T09:00:00.000Z",
    updated_at: "2023-11-12T09:00:00.000Z",
  },
];

export const referrals: Referral[] = [
  {
    id: "ref-1",
    claim_id: "CA-10234",
    policyholder: "Michael Hart",
    loss_type: "Fire",
    referred_partner: "Rapid Restore",
    referral_date: "2023-10-16T09:00:00.000Z",
    status: "in_progress",
    progress: 65,
    last_update: "2023-11-20T14:00:00.000Z",
  },
  {
    id: "ref-2",
    claim_id: "CA-10235",
    policyholder: "Jessica Chen",
    loss_type: "Storm",
    referred_partner: "ClearSky Roofing",
    referral_date: "2023-09-23T09:00:00.000Z",
    status: "awaiting_approval",
    progress: 80,
    last_update: "2023-11-18T11:00:00.000Z",
  },
  {
    id: "ref-3",
    claim_id: "CA-10238",
    policyholder: "Samuel O'Neil",
    loss_type: "Fire",
    referred_partner: "Rapid Restore",
    referral_date: "2023-10-02T09:00:00.000Z",
    status: "in_progress",
    progress: 45,
    last_update: "2023-11-19T16:00:00.000Z",
  },
  {
    id: "ref-4",
    claim_id: "CA-10236",
    policyholder: "Rafael Gomez",
    loss_type: "Water",
    referred_partner: "EverDry Mitigation",
    referral_date: "2023-08-11T09:00:00.000Z",
    status: "completed",
    progress: 100,
    last_update: "2023-11-10T10:00:00.000Z",
  },
  {
    id: "ref-5",
    claim_id: "CA-10237",
    policyholder: "Emily Davis",
    loss_type: "Wind",
    referred_partner: "Northwind Construction",
    referral_date: "2023-11-03T09:00:00.000Z",
    status: "pending",
    progress: 10,
    last_update: "2023-11-22T08:00:00.000Z",
  },
];

export const workflowStages: WorkflowStage[] = [
  {
    id: "stage-0",
    title: "Lead / Inquiry",
    summary: "Capture new lead, contact info, loss basics, and auto-assign adjuster.",
    outputs: ["Lead record", "Call + schedule tasks", "Status: New → Contacted"],
    status: "incoming",
  },
  {
    id: "stage-1",
    title: "Pre-Claim Triage",
    summary: "Qualify coverage, urgency, and decide if fit; convert to client + claim in one click.",
    outputs: ["Fit decision", "Coverage notes", "Triage notes template"],
    status: "incoming",
  },
  {
    id: "stage-2",
    title: "Engagement & Agreement",
    summary: "Send PA agreement, collect signatures, and policy copy; unlock claim creation.",
    outputs: ["Signed agreement", "Policy info", "Contingency %", "Doc storage"],
    status: "active",
  },
  {
    id: "stage-3",
    title: "Claim Setup",
    summary: "Create claim dashboard (new or existing); capture claim number, carrier contacts, limits.",
    outputs: ["Claim record", "Carrier adjuster", "Initial tasks: schedule inspection, request policy"],
    status: "active",
  },
  {
    id: "stage-4",
    title: "Inspection & Documentation",
    summary: "Schedule inspection, capture photos, scope notes, and third-party vendor requests.",
    outputs: ["Inspection event", "Photo/video set", "Scope notes per room", "Vendor requests"],
    status: "active",
  },
  {
    id: "stage-5",
    title: "Estimate & Package",
    summary: "Prepare estimate versions, narrative, expert reports, and readiness checklist.",
    outputs: ["Estimate v1/v2", "Photo report", "Narrative", "Package checklist"],
    status: "active",
  },
  {
    id: "stage-6",
    title: "Submit to Carrier",
    summary: "Send package, log communication, set auto follow-ups for response SLA.",
    outputs: ["Submission log", "Follow-up timer", "Carrier contact"],
    status: "loop",
  },
  {
    id: "stage-7",
    title: "Carrier Response Loop",
    summary: "Track responses, offers, denials, reinspections, supplements, and negotiation log.",
    outputs: ["Negotiation log", "Carrier offers", "Supplements", "Tasks: respond/prepare"],
    status: "loop",
  },
  {
    id: "stage-8",
    title: "Settlement",
    summary: "Record final numbers by coverage, compare before/after, compute PA fee.",
    outputs: ["Settlement record", "Coverage breakdown", "PA fee calc"],
    status: "closing",
  },
  {
    id: "stage-9",
    title: "Payments & Vendors",
    summary: "Track checks, endorsements, vendor coordination, and fee collection.",
    outputs: ["Payment ledger", "Vendor status", "Fee tracking"],
    status: "closing",
  },
  {
    id: "stage-10",
    title: "Closeout & Follow-Up",
    summary: "Final checklist, freeze numbers, request reviews, and add to retention segment.",
    outputs: ["Closeout checklist", "Client feedback", "Review request"],
    status: "closing",
  },
];

export const carrierLoop: CarrierLoopStep[] = [
  {
    id: "loop-1",
    title: "Initial Response",
    summary: "Carrier estimate/offer arrives or denial/request for info is issued.",
    tags: ["Offer", "Denial", "RFI"],
  },
  {
    id: "loop-2",
    title: "Gap Analysis",
    summary: "Compare carrier vs PA estimate; identify scope gaps and coverage issues.",
    tags: ["Compare", "Scope", "Coverage"],
  },
  {
    id: "loop-3",
    title: "Supplement Needed",
    summary: "Prepare and send supplements, rebuttals, and expert support.",
    tags: ["Supplement", "Rebuttal", "Evidence"],
  },
  {
    id: "loop-4",
    title: "Reinspection / Events",
    summary: "Track reinspections, EUO, mediation, appraisal, or litigation triggers.",
    tags: ["Reinspection", "Mediation", "Appraisal"],
  },
  {
    id: "loop-5",
    title: "Negotiation Log",
    summary: "Structured log: date, party, position, documents referenced, next step.",
    tags: ["Log", "Tasks", "Follow-up"],
  },
];

export const crossCutting = [
  {
    title: "Communication Log",
    points: ["Log calls/emails/texts", "Filter by party and type", "BCC ingestion"],
  },
  {
    title: "Task & Reminder Engine",
    points: ["Carrier SLAs", "Proof-of-loss deadlines", "Reinspection follow-ups"],
  },
  {
    title: "Document Management",
    points: ["Tags + versions", "Per-claim repository", "Policy/estimate letters"],
  },
  {
    title: "Roles & Permissions",
    points: ["Internal vs client portal", "Partner/vendor access", "Private negotiation notes"],
  },
  {
    title: "Dashboards & Reporting",
    points: ["Pipeline by stage", "Financial metrics", "Referral source performance"],
  },
];

export const swimlanePhases: SwimlanePhase[] = [
  {
    id: "lane-1",
    title: "Lead & Intake",
    adjuster: "Logs lead, schedules consult",
    client: "Provides loss basics",
    carrier: "N/A",
    vendor: "Referrers send lead",
  },
  {
    id: "lane-2",
    title: "Triage",
    adjuster: "Qualify coverage/fit, check prior claim",
    client: "Shares docs/letters",
    carrier: "May have open file",
    vendor: "May have done emergency work",
  },
  {
    id: "lane-3",
    title: "Engagement",
    adjuster: "Send PA agreement / LOR, collect policy",
    client: "Signs agreement, shares policy",
    carrier: "Notified informally",
    vendor: "Introduced as contractor",
  },
  {
    id: "lane-4",
    title: "Claim Setup",
    adjuster: "Create claim, file FNOL, record carrier adjuster",
    client: "Authorizes carrier comms",
    carrier: "Creates claim, assigns adjuster",
    vendor: "Provides initial estimate/invoice",
  },
  {
    id: "lane-5",
    title: "Negotiation Loop",
    adjuster: "Supplements, calls/emails, reinspections",
    client: "Approves strategy, attends reinspections",
    carrier: "Issues offers/denials, requests info",
    vendor: "Supports reinspections, updates estimates",
  },
  {
    id: "lane-6",
    title: "Settlement & Funds",
    adjuster: "Log settlement, collect PA fee, coordinate vendors",
    client: "Endorses checks, pays vendors/PA",
    carrier: "Issues checks, closes file",
    vendor: "Performs work, invoices and gets paid",
  },
];
